from __future__ import annotations

STAGES = (
    "s01_baseline_data",
    "s02_trimodal_baseline",
    "s03_conversion_labels",
    "s03_mmse_conversion",
    "s03_modality_conversion",
    "s04_individual_models",
    "s04_feature_selection",
    "s05_stage2_dataset",
    "s05_stage2_model",
    "s06_combined_dataset",
    "s06_combined_model",
    "s07_combined_all_dataset",
    "s07_combined_all_model",
    "s08_stage2_all_dataset",
    "s08_stage2_all_model",
    "s09_cross_validation",
    "s09_readme_table",
    "s10_ambiguous_specialist",
    "s11_confidence_bands",
    "s12_boundary_distance",
    "s13_modality_handoff",
    "s14_fusion_handoff",
)
